### ISSUE TITLE
Define data fields in Data Register

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#104]
Define all fields within the data register in plain language that can be shared with subscribers and users.

**Comment by ndelraye** [comment]
![Image](https://github.com/bcgov/parks-data-register/assets/26172886/8416013c-4c10-46d3-a179-d1d1d9860ca9)

**Comment by ndelraye** [comment]
[https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProject%5D%20Parks%20Data%20Services/data%20register%20definitions.docx?d=w021e9b799acc4d6cb7d59250ded172f6&csf=1&web=1&e=p4vxQe](url)
