### ISSUE TITLE
Include invalidation in FE Prod deployment pipelines

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#105]
Aggressive browser caching is sometimes causing issues for users who are on stale versions of our sites after breaking changes are pushed.

We should fire off an invalidation every time we push our front ends to prod so that these browsers are forced to reload the latest site.

We only need to do this in prod. 

## Acceptance Criteria

- Update our GH actions to fire off an invalidation upon successful prod deployments (A&R DUP and PDR front ends).

**Comment by manuji** [comment]
Hi @cameronpettit , could you please add testing notes to this ticket? I don't see any PRs in A&R for this, is this just a setting you do on PROD? Also what type of testing is required? 

Thank you!

**Comment by cameronpettit** [comment]
You can check that CloudFront performed an invalidation on deploy.
![image](https://github.com/bcgov/parks-data-register/assets/71421099/b24ccd8c-1d72-4b12-9bd8-e1b96c243aca)
Looks like the one you did recently was successful.

**Comment by manuji** [comment]
Thanks @cameronpettit for the comment. I will check this on AWS.

**Comment by manuji** [comment]
Tested on PROD: Pending
* Verified that this task has been completed on park data register PROD: **Passed**

@marklise , I checked A&R- PROD cloud front, and looks like this task has not been done there. I will re-assign this to you and move to Todo. 



https://github.com/bcgov/parks-data-register/assets/65190263/ada639eb-096a-4960-aab2-f16e386f990b



Note: Pending testing on DUP-PROD (no PROD deployments done to verify this yet)

**Comment by manuji** [comment]
Tested on DUP PROD: **Passed**
* Verified that the invalidation has happened on the Admin and Public sites. 
* Pending testing on A&R. 


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/dd54262f-bdbe-4073-9f67-6c0f8874f30d)

**Comment by manuji** [comment]
Tested on A&R PROD: **Passed**
* Verified that this task has been completed on A&R as well.

**Comment by JLWade** [comment]
moving to done
