### ISSUE TITLE
Update CloudFront to distribute from local region first

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#106]
Our current SAM S3/CloudFront configuration distributes our front ends to the global AWS domain (s3.amazonaws.com) first, which then percolates to the regional domains. This can lead to some lengthy delays between a successful deployment and actually seeing the changes live in the regional domain.

We can update our SAM template.yaml to distribute first to the regional domain (s3.ca-central-1.amazonaws.com) and effectively remove this delay.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html

## Acceptance Criteria

Change SAM template.yaml to reference `RegionalDomainName` instead of `DomainName` where the CloudFrontDistribution - Origin is defined:

```
Origins:
          - Id: !Ref DistS3Bucket
            DomainName: !GetAtt DistS3Bucket.RegionalDomainName
```

**Comment by marklise** [comment]
Done as of commit #e09ab0f194c5d8619ded60eee6d243d15d2353e4
