### ISSUE TITLE
Spike: How to Configure Access Controls for Register

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#11]
## Description:

Spike on what methods we can use to configure access controls for the data register. 

Options:
- status quo: keycloak custom realm
- cognito

Configure access controls for who can view statuses of parks.
Sys admin = all
Open = legal and repealed NOT pending (also does not see notes field)

## Acceptance Criteria:

- pro/con decision matrix to inform decision

**Comment by marklise** [comment]
Resolving this as done.  We are currently using Keycloak shared realm for authorization access.  Users who do not provide a JWT on their api calls (web app users or api) are limited only to parks that are `repealed` or `established`
