### ISSUE TITLE
Automate "Move to Next Sprint" in Github

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#113]
At the moment, GitHub doesn't automatically end a sprint and move incomplete issues to the next sprint, leading to manual efforts from team to move the issues over.

Can we investigate implementing some sort of GitHub action to automate this process.

Below are some links I found on the GitHub Community page discussing the need for GitHub to add this functionality, as well as a GitHub action a community member has created (not sure if we can leverage).

https://github.com/orgs/community/discussions/16222
https://github.com/marketplace/actions/move-to-next-iteration

Alternatively:
A github action can be setup to be manually run.  It would fetch the issues, find the appropriate items in the TODO column, and update their sprint association.

An api call to the gh api graphql endpoint can be made to get all issues, and then the script can parse through the states of the issues returned, and move them to the next sprint by calling the appropriate api endpoint to update the issue and set the `Sprint` field to the next sprint in question.

The following query can be used to get a list of the first 20 issues in the project and pagination information (for subsequent pages)
```

  gh api graphql -f query='
  query{
  organization(login: "bcgov") {
      projectV2(number:49) {
        
        id
        title # Project title
        
        items(first: 20) {
          nodes {
            databaseId
						id
            content {
              __typename
              ... on Issue {
                # Find associated issue with Project item:
                url
                #... all fields associated with an Issue are available
              }
            }

             fieldValues(first: 20) {
            nodes {
              ... on ProjectV2ItemFieldSingleSelectValue {
                field {
                  ... on ProjectV2SingleSelectField {
                    name
                  }
                }
                name
                id
              }
            }
          }
        }
        pageInfo {
          endCursor
          hasNextPage
        }
      }
      
    }
  }
}'

```

**Comment by LindsayMacfarlane** [comment]
Hi @Dianadec - is this ticket still needed?

**Comment by Dianadec** [comment]
@LindsayMacfarlane  nope - the manual move over is good for checking in on tickets as part of the workflow, so i'd say this isn't worth moving forward on.

**Comment by LindsayMacfarlane** [comment]
Added won't fix label and moving to done.
