### ISSUE TITLE
[L] Set up rate limiting and controls on api

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#122]
Create generic api token for anyone accessing api - open and highly limited.
For specific users - they need to ask to get a secret token created for them to use api at specific rates.

## Acceptance Criteria

API Gateway:

- Usage plan needs to be created first:

![Image](https://github.com/bcgov/parks-data-register/assets/51633/16f98140-48c8-4784-8b67-bead5c3f4662)

- All endpoints (except config) will need to have their flags set to require an API key

Initial limits should be rate: 50, burst: 100, Quota: 1000/day

## Notes

- For each consumer of the DR, an api key needs to be created and associated with the usage plan above.
- Authorizer changes may be required given current approach of authorizer PR. See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-key-source.html for more details.

QA/Testing:
- See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-key-source.html for more details.

**Comment by marklise** [comment]
Removed section about optional keys - not possible without lambda edge.

**Comment by manuji** [comment]
Tested on Dev, TEST & PROD: **Passed** ✅
* Verified that, without an API key, users cannot get results through API calls on all 3 environments. Not even the Public search (Authorization = None)
* Verified that all 3 environments have Usage limits set on AWS API Gateway. 
* Passing to PO review.

**Comment by JLWade** [comment]
moving to done
