### ISSUE TITLE
[M] View All Available Park Name Info and Apply Permissions to private fields - API

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#136]
Developer who picks up #28  to add Acceptance Criteria details to this ticket - as well as a t-shirt size/estimate.

Most of this work has been completed - remaining piece is around redacting "notes" field for public users (ie. this is only possible to view for sysadmin role).

**Acceptance Criteria / Dev Tasks:**
- For public users, redact 'notes' field

**Notes:**
- query for 'give me all the parks that are historical, current, pending' (status flag; bring in public vs private; public doesn't get pending or cancelled) is done in query api ticket
- ensure search and resource endpoint are accounted for 
  - could potentially do this for search via different index's OR have search redact based on role/main index
- this ticket blocks #28  and needs to be completed in parallel

**Comment by JLWade** [comment]
Done as part of api query ticket

**Comment by marklise** [comment]
Fixed as of 5c351645b1757687191b328f707381fdaa8da5ed.

Closing.

**Comment by manuji** [comment]
Tested on TEST: **Passed** ✅
* Using Postman verified that the "Notes" are not displayed to the public users with the header "Authorization=None".
* Passing to PO review. 


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/8e79ef20-f1ba-46ac-a317-7f08073928df)

**Comment by JLWade** [comment]
Moving to done - and will validate in UI portion of this work
