### ISSUE TITLE
Lambda Authorizers

### ISSUE THREAD

**Issue by danieltruong** [bcgov/parks-data-register#137]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

AC:
Lambda authorizer is implemented to protect our data. At this time, we will have public and sysadmin.

**Comment by manuji** [comment]
@danieltruong could you please add QA notes for this ticket, I need your help to figure out what to check and where. Thanks in advance!

**Comment by manuji** [comment]
@danieltruong I dug through and found details here: https://github.com/bcgov/parks-data-register/pull/144, I will try to test what is mentioned there and reach out to you if I need more information.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that without authorization, the API calls will not return data.

**Comment by JLWade** [comment]
moving to done
