### ISSUE TITLE
[L] API side of front-end that reflects edit/updates

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#138]
Implement API to support the the following actions

- update current park name data (existing current park name becomes historical, new current park name in its place)
- update park name data without cycling current park (existing current park remains current park, but properties are updated)

Question: Who has permissions to do these actions? Answer: Sysadmin

## Acceptance Criteria

- API functionality is in place to perform the above actions, permissions are enforced.
- Audit table tracks changes appropriately (minor changes)
- Change log tracks changes appropriately (major changes)
- Postman updated
- HTTP put

Dev AC:
- api key for admin portal is created to facilitate use of parkname data register api in the park name data register admin portal

## Notes
Refer to #29 for more information.
Api Backend for #30 #133 #132

**Comment by JLWade** [comment]
moving to done
