### ISSUE TITLE
[M] Add "search terms" to data model for data register

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#145]
This ticket is to add the search term field to the data model so that users can use alternate words to search for a park name. This will utilize the work done around search in #134 to enhance search capabilities.

**Dev AC:**
- Update Model in workspace file - documentation etc.
- Integrate (find hooks) with opensearch functionality built in #134 

## Acceptance Criteria
- data model includes Search Terms as a free form text field (string)
  - this field supports extra text that should be used when the backend is searching for stuff
  - documentation in github is updated
- search will be able to look at all values in this field to bring up a park name

## Notes
- for users (devs via api or manually) - they can look at search terms or legal, display, and historical name for searching via backend search magic (indexing)
- UI for this field is in #28 
- blocked by #134

**Comment by manuji** [comment]
Tested on TEST: **Pending**

* Checked the DynamoDB and didn't find a field for the Search terms. 

FYI @marklise , please let me know if it has a different name on DynamoDB.

**Comment by marklise** [comment]
The data model has been updated (nosql workbench file). As for terms in the database, that is not complete without a UI to wire up front-end changes. The only verification here is to see that the data model documentation has been updated.

**Comment by manuji** [comment]
Tested on the GitHub: **Passed** ✅
* Verified that the new field "searchTerms" has been added. 
* Link to the data model documentation: https://github.com/bcgov/parks-data-register/blob/main/pdr-api/docs/nosqlWorkbenchDataModel.json
* Passing to PO review. 



![Image](https://github.com/bcgov/parks-data-register/assets/65190263/f0e5b56d-9d25-45e5-a87e-a37b0c0e0f5d)

**Comment by JLWade** [comment]
moving to done
