### ISSUE TITLE
[S] Spike: Document a solution to provide real-time updates to 3rd party subscribers of the data register.

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#178]
We should look into registering webhooks from 3rd party subscribers so that we can call the hook once a data point has changed in the register.  We'll need to store the webhooks registered for 3rd parties in a DB and go through them once a major/minor change has been made.

Another solution may be to setup a public SQS that people can openly self serve/subscribe to (maybe less work)

### Acceptance Criteria
- Make decision and document approach
- Create implementation ticket

**Comment by ashley-dhillon** [comment]
@marklise when you have time, can you add some details to this ticket so we can chat about it at backlog refinement tomorrow.

**Comment by ashley-dhillon** [comment]
@marklise just tagging you again on this ticket - are you able to add details to the description, please and thanks!

**Comment by marklise** [comment]
Completed.  Details are in the following ticket: https://github.com/bcgov/parks-data-register/issues/306
