### ISSUE TITLE
[S] Ability to login to Data Register with IDIR only

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#24]
As the park name registrar, I need to be able to securely login to the register so that I can make changes to park names.

This ticket is to enable the front end login for users into the registrar - this should look and feel like our other products but will only have idir authentication available. A user (with sysadmin permissions) should be able to hit a page to enter their idir credentials and it will enable them to login and see the register (at this point just "hello world" app). 

**Acceptance Criteria:**
- authenticator login is available (keycloak)
- Sysadmin role has read/write permissions - can do all the things
- IDIR login is the only option available
- I can be given sysadmin role and login with my idir to see a skeleton page
   - skeleton page includes usual bc parks theme header, footer, logo, colors, fonts from #39 

Notes:
#40

**Comment by manuji** [comment]
@danieltruong , could you please provide the URLs to the environments for testing?

**Comment by manuji** [comment]
Blocked by https://github.com/bcgov/parks-data-register/issues/35

**Comment by ashley-dhillon** [comment]
@manuji environment URL's can be found in Confluence here - https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Park+Names

**Comment by danieltruong** [comment]
Dev: https://dbx86hob7f9t1.cloudfront.net/
Test: https://dy4iqvs3p7liq.cloudfront.net/
Prod: https://de7qrsssa73vh.cloudfront.net/

**Comment by manuji** [comment]
Hi @danieltruong , there is this alert box displayed when I try to login with my IDIR. It's not something new I am seeing but would like to raise it for our product to see if we can get rid of it. Here is an image of the alert box:


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/89f7a998-f434-44b3-a9c7-cee592f06f8e)

Let me know your thoughts.

**Comment by manuji** [comment]
Tested and verified that users can access Dev. Test and PROD environment with their IDIR. 

Passed ✅

**Comment by JLWade** [comment]
got unauthorized and was able to give myself the correct role to log in - looks good! moving to done
