### ISSUE TITLE
DR-> Missing tooltips and incorrect sort order of the search results

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#243]
Scenario:

* Navigate to the Data register Admin portal: https://test-data.bcparks.ca/admin/protected-areas
* Navigate to the "Find a protected area page
* Check the UI components and verify that it's implemented as per Figma.
* Also check the UI components after searching for a search term. 

Issues:

1. Missing the action button tooltips. 
2. The Search data is not sorted and displayed in ascending order. 

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/f298b231-e36b-4dcb-8f01-7233031af98d)

**Comment by JLWade** [comment]
Whoops - thought I added a comment. 

As discussed in another channel, @meredithom is taking a look at this to update designs or ticket depending on where things diverged over the sprint.

**Comment by JLWade** [comment]
@meredithom seems like most of this one is getting addressed currently is that right?
@danieltruong 
We can bring this one in or delete it as a duplicate.

**Comment by JLWade** [comment]
@manuji thinking we can address this one at the same time that #294 is being tested. 
FYI @meredithom @danieltruong

**Comment by manuji** [comment]
@JLWade I will pull this to the current sprint to test.

**Comment by manuji** [comment]
I updated the ticket leaving only the functional bugs.

**Comment by marklise** [comment]
@manuji @JLWade `Check the UI components and verify that it's implemented as per Figma.
` What is the figma link in question and inside the figma the design for this please.

**Comment by JLWade** [comment]
1.0b here: https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=101-12&mode=design&t=bgNR19X7IFatY6ml-0
@manuji is that correct?

**Comment by marklise** [comment]
`Missing the action button tooltips.` what does this mean?
`The Search data is not sorted and displayed in ascending order.`  Ascending what exactly, by which field?

I cannot access figma - hence asking for designs to be pushed into tickets:
![image](https://github.com/bcgov/parks-data-register/assets/51633/af3d10b6-5b4e-4baf-a206-23b599fdd4fe)

**Comment by JLWade** [comment]
Trying to get your permissions updated - her eis the descriptions I think Manuji is looking at
![image](https://github.com/bcgov/parks-data-register/assets/38668130/14f3a9fa-650e-490d-8e57-90345b25d729)

**Comment by manuji** [comment]
Hi @marklise & @JLWade sorry for the late reply. 

@marklise here is the direct link for the requirements: https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=734%3A10255&mode=design&t=6l9n8F08xwzDmdLe-1

@JLWade thanks for attaching the screenshot and @marklise that screenshot should have all the answers to your questions.

**Comment by marklise** [comment]
It is not possible to style the bootstrap tooltip exactly how the designs have it:

![image](https://github.com/bcgov/parks-data-register/assets/51633/7a4d54e9-8489-428f-be8d-935e574ed752)


## There are only two ways:


**Option 1:**  White Background (no border)

![image](https://github.com/bcgov/parks-data-register/assets/51633/d8bdf92c-7703-40be-8df8-a858adfeb23e)

**Option 2:** Black Background (no border)

![image](https://github.com/bcgov/parks-data-register/assets/51633/fcfc368a-d06d-4f07-958c-4e9f25565241)

Need to choose an option and update designs accordingly. @JLWade @janemoxd

**Comment by JLWade** [comment]
Will let @meredithom or @janemoxd decide - I am good with either, small preference for option 2, only because I can see it better

**Comment by janemoxd** [comment]
Yes, if these are our choices, then **option 2 please**. 

@meredithom - please let me know if you have time to update the designs. If not, I can prob find the time at some point. Also, this would be a good first/early component for our design library, as it's already defined for us.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that the issue with the tooltip has been fixed. 
* I will create a separate bug for the other issue mentioned in the description as it has not been fixed yet. 

fyi @marklise & @JLWade 



![Image](https://github.com/bcgov/parks-data-register/assets/65190263/fdc37864-a89d-4544-94d8-5c0a21608501)
