### ISSUE TITLE
API -> Missing the option to update the Repealed Date

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#249]
Scenario:

Navigate to the postman and try to edit the repealed date information of a record with status= Repealed.

Issue:
* Nothing can be edited if the status is set to repealed, at the moment 

Expected:
* There should be an option to edit the repealed date if a user makes a mistake. refer: https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=911%3A5572&mode=design&t=yLmy4jMZxDDjN7RS-1

**Comment by JLWade** [comment]
Thanks for catching this @manuji!

Just confirming, when you tested in postman nothing could be edited on repealed parks?
They wont be able to change status again but they will have minor edits to date of repealed and add notes.

**Comment by JLWade** [comment]
After chatting bringing this into the current sprint to resolve - enabling minor edit on repealed status protected areas

**Comment by manuji** [comment]
Tested using Postman and DynamoDB on TEST: **passed**
* verified that this feature has been implemented and working fine.
* passing to PO review.
