### ISSUE TITLE
[XXS] Manage other users access

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#25]
As a data register admin user, I need to be able to grant permissions to people who will be able to access to register so that they can do their job and manage park names.

Minimal work to be done in code - most of this will be handled by redhat and keycloak.

**Acceptance Criteria:**
- ability to add new administrators (sysadmin)
- ability to manage permissions via keycloack/redhat
- can grant a user keycloak realm access so that they can grant others permissions

Notes:
- blocked by #40 
- relates to #24

**Comment by manuji** [comment]
Tested on TEST and PROD: **Passed**
* Verified that access/permission can be added to users from Keycloak. 
* Ready for PO review.

**Comment by JLWade** [comment]
viewed in keycloak - moving to done
