### ISSUE TITLE
[L] Search by legal name or parkID

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#26]
As a the park name registrar, I need to search for a protected area so that I can view and/or edit it's name. This ticket is to build out the register admin portal search page and functionality.

Figma designs complete and signed off by all team members:
* ![Image](https://github.com/bcgov/parks-data-register/assets/26172886/6e87c972-04e0-4e5c-9cb4-e03ff8224a2e)
* ![Image](https://github.com/bcgov/parks-data-register/assets/26172886/42c1d8f5-0159-4c48-a71d-75b1ce8b2649)
* ![Image](https://github.com/bcgov/parks-data-register/assets/26172886/a6dce82d-1939-455d-b028-34f43bace20c)
* ![Image](https://github.com/bcgov/parks-data-register/assets/26172886/2a753e3a-d8cc-439f-8336-7b6ea9a25a33)

### Text Search
Allow all characters. 
User can search for any string.
All fields will be searched.
  - ORC/ParkID
  - Legal name
  - Status
  
### Type Filter
This refers to the type of record. 
For Release 1, there is only one type: Protected area
This filter can be used by itself or in combination with search and filters.

### Protected Area Filter
For Release 1, values are:
Any (default status)
Established
Repealed 

Cancelled / Deleted will not become a status as we won’t be saving this info in the system.

This filter can be used by itself or in combination with search and filters.

### Default Search Results View
By default, no results will be shown. We will only show results after a user clicks search.

See following UIs for various search result scenarios.

- Api updates to be completed via #134 
  - API can filter by existence of audio clip

- Design should match Figma design files

## Notes
as per conversation the original name search and Park ID search fields were combined into one search field called Search

**Comment by manuji** [comment]
Tested on TEST environment: Pending
* Verified that the feature and screens have been implemented.
* The defects have been reported in separate bug tickets -> https://github.com/bcgov/parks-data-register/issues/243

**Comment by JLWade** [comment]
text search is working as expected, filters piece is in #244 
moving to done

I did notice the first search is a bit slow but then super fast after that, I'm guessing the first search is the first call to the db and then it's quicker after because it's remembering the call.

**Comment by JLWade** [comment]
Current search searches notes field, we have #248 to remove that from the search on this page.
