### ISSUE TITLE
Display/Search Protected Area ID with leading zeroes

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#264]
When displaying protected area IDs in the front end, it has been requested that the leading zeroes be displayed ( ie `0001` vs `1` for Strathcona). Additionally, Opensearch must return hits if given a query including leading zeroes. 

A quick, short term solution to get this display data to all protected area UIs AND give Opensearch the functionality to search with leading zeroes is to update the data model to include a new field that stores the leading zero id.

**AC**

- Update the data model to include a new field `displayId` that contains the 4-digit zero-padded pk. 
- Perform a migration to update the databases with the new field.

**Comment by cameronpettit** [comment]
@JLWade @dtruong @marklise FYI

**Comment by cameronpettit** [comment]
@manuji test/prod will need a migration when this gets merged

**Comment by JLWade** [comment]
leading 00's look good! moving to done
