### ISSUE TITLE
Prevent major change if neither status nor legalName change

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#292]
Currently a major change can be performed without changing the `legalName` in the API. 

Expected behavior: a major change necessitates either a changed `legalName` field or a changed status.

**AC**

- Major changes are prevented if there is no status change or legalName change.

**Comment by manuji** [comment]
Tested using Postman: **Passed**
* Verified that this update is working fine. 
* Passing to PO review.

**Comment by JLWade** [comment]
working as expected - moving to done
