### ISSUE TITLE
DR-Admin Current State - 2023/12/14

### ISSUE THREAD

**Issue by danieltruong** [bcgov/parks-data-register#294]
# Acceptance Criteria
- Implemented UI matches designs attached to this ticket.
- Buttons/links link to the correct pages.
- Search returns expected results: searches on all fields except notes.
- Search filters update results.
- Can make minor, major, and repealed edits. Edits show up correctly after save.
- Upon editing, required fields must be filled in and will prevent saving if left blank.
- Overlay with changes is displayed after saving.
- After a legal name change, the old name appears as a historical entry on 1.1.

# Home page
## 0.0
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/949efe23-50c5-49f0-abb6-71d9fb8a975f)

## 0.1
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/9fad5f85-d526-42da-9cd8-f05ae06103f7)

# Protected Area Search
## 1.0
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/819d7bd7-4a89-4733-8559-01d3855b91d7)

![Image](https://github.com/bcgov/parks-data-register/assets/15185966/6c25c287-cf4c-490a-90c4-47d4a10cee9f)

**Search Filter:** Allows all characters. User can search for any string. All fields will be searched excluding notes.
By default, no results will be shown. We will only show results after a user clicks search. The filters initial state, unchecked, will return all results. 

The eye icon links to 1.1 for that protected area
The pen icon links to 1.1.1

# Protected Area Details
## 1.1
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/102dcb64-7fee-4bbd-9581-7558797b4865)

![Image](https://github.com/bcgov/parks-data-register/assets/15185966/7fac806d-8902-42f3-8586-c67382332f0b)

Currently displays Legal Name details, Search terms, and associated Historical Names.
Clicking edit will take you directly to 1.1.1.1 or 1.1.1.3 if protected area has a repealed status.
If park is repealed, shows repealed date.

# Protected Area Edit Landing Page
## 1.1.1
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/7a405699-878e-4020-afd9-1f2dfbfa8623)

**Make minor edits** links to 1.1.1.1
**Change legal name** links to 1.1.1.2
**Set status to repealed** links to 1.1.1.3

# Protected Area Edit
**Legal name is the same as Display name:** when checked, display name will copy the value from legal name. If unchecked, the form field for display name will appear. 
**Cancel button:** On click, take user back to 1.1.1 Edit record - choose edit type
**Save button:** On click, display confirmation overlay displaying changes

## 1.1.1.1 Minor
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/5a29d5db-784a-4be1-9013-210de519c481)

![Image](https://github.com/bcgov/parks-data-register/assets/15185966/1d1691d9-4057-4d12-a35d-6623b4f49f7a)

![Image](https://github.com/bcgov/parks-data-register/assets/15185966/a0bec79a-f771-4e04-9d84-ada2e23899f2)

## 1.1.1.2 Major
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/13498091-b19c-4c66-9217-d37d783c8491)

![Image](https://github.com/bcgov/parks-data-register/assets/15185966/5eac3a49-1cf2-4e8a-9649-567943494c39)

## 1.1.1.3 Repeal

![Image](https://github.com/bcgov/parks-data-register/assets/15185966/82091216-f920-4c5d-847e-5c6392e19ad2)

# Other testing notes
The following link is for the wiki of our DR-Admin:

https://github.com/bcgov/parks-data-register/wiki/PDR%E2%80%90Admin

The section on routing may be relevant to this ticket.

**Comment by manuji** [comment]
Tested on TEST: In progress. 
* Verified screen 0.0 looks good and passed.
* Verified screen 0.1 has been implemented but a separate bug has been reported with all the UI issues -> https://github.com/bcgov/parks-data-register/issues/319
*

**Comment by JLWade** [comment]
moving to done
