### ISSUE TITLE
View protected area search results limit the reuslts to 10 and missing the option to load more or paginate

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#295]
Scenario:
* Navigate to the park data register admin portal and log in as an Admin user
* On the Find a protected area page, search for a keyword that should result in more than 10 records. (eg: Lake, park, Mountain)
* Check the search results

Issue:
* The search results only show up to 10 records and there is no indication of  another option or a way to get to the rest of the results. 

Expected:
* There is a screen for this scenario, but indicated as removed: https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=388%3A5511&mode=design&t=xaXLrb79mm2SUYUj-1.

**Comment by cameronpettit** [comment]
FWIW this isnt so much a bug as it just hasn't been implemented yet. I'm looking into the API side to handle result pagination. After that is finished we can implement a `load more` feature on the front end.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* verified that this issue has been fixed. 

FYI @JLWade
