### ISSUE TITLE
Search List not showing up to date info

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#299]
To replicate:
- go to DR protected area search
- look for golden 
- notice golden eyes comes up, click it
- details page shows golden ears (which is most up to date)

Bug:
- search results showing old name "golden eyes" but park name should be golden ears
- open search caching is not updating

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that this issue has been fixed. 
* Passing to PO review.

**Comment by JLWade** [comment]
search list is updating now - moving to done
