### ISSUE TITLE
Update Protected Area PUT to only require relevant fields

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#304]
With versioning now implemented with our PA PUT API endpoints, we can remove the requirement that every possible field must be submitted in the request body - Leaving this in has been a source of error in connecting the API to the Front End cleanly. We should remove the requirement to make things easier for devs and consumers alike

AC:
- when performing major, minor or repealed edits, the API should only require the relevant fields.
- Mandatory fields are `effectiveDate`, `lastVersionDate`, and `legalName` (if not a repeal change). 
- All other fields are not mandatory but will be applied to the update if they are provided - that means if an empty field is provided, the resulting record's field will also be empty.

**Comment by cameronpettit** [comment]
@JLWade FYI

**Comment by manuji** [comment]
Tested on TEST using Postman: **passed**
* verified that when the mandatory fields are missing a proper error message is displayed explaining what is mandatory for a successful API call. 
* Verified that the PUT actions for Major, Minor, and Repeal are working as expected when mandatory information is provided. 
* Verified if no values passed for the optional fields, the values won't get impacted unless the field is added to the API call without a value. 
* Passing this to PO review. 


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/ede5c693-96d9-42e9-9b7c-c0c22fc90011)
![Image](https://github.com/bcgov/parks-data-register/assets/65190263/492fcf5d-6ceb-4d09-be58-6501f4d2b442)
![Image](https://github.com/bcgov/parks-data-register/assets/65190263/dc93e3a4-eb7a-4bc4-a3af-8680575f79cc)

**Comment by JLWade** [comment]
moving to done
