### ISSUE TITLE
Update Figma - DUP, A&R, and DR files with Admin Library Components

### ISSUE THREAD

**Issue by meredithom** [bcgov/parks-data-register#315]
**Acceptance criteria:**
- Figma files are using the Admin Library assests (font's colours, logos)
- Common Components are replaced with the updated library

**Note:**
DUP is currently comprised of multiple screenshots, updating the DUP Figma will require many pages to built from scratch 

Blocks #469  and #3 3 5

**Comment by meyerdarcie** [comment]
Moving to done - FYI @meredithom
