### ISSUE TITLE
[L] Create Data Model for Name Register

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#33]
This ticket is to develop our initial data model for the park name register.

Some data elements discussed for minimal viable dataset: (* = mandatory) - _this list has differed from original thinking of MVD from months ago_
- ORCS* (has to manually entered as this is numbering is used for other systems outside of BC Parks)
  - new information states this may be autogenerated by another microservice
- Site Number (ie. ORCS-1)
- Name Type* (Legal, Display, Phonetic)
   -  Legal Name*
   -  Display Name
   -  Phonetic Name
- Status* (current, repealed) - this is status of park
- Legal Name Change Date* (system will need to track date user changed it, but actual legal name change date will reflect what is in OIC - for example, Aug 5th legal name changed, but I wasn't able to change it in system until the 8th)
- Audio Clip
- Notes (free form text)

This ticket includes discussions and research into what the data model will be composed of from business and data register perspective. 

**Acceptance Criteria:**

- data model diagrams are documented and there is a link to these documents within repo
- internal documentation (https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Park+Names) has link to diagrams and any confidential information (if any)
- data model and database is ready to be used for development

**Notes:**
- use wireframes and user research to inform model
- this issue will likely involve lots of discussion and back and forth
- relates to #34

**Comment by manuji** [comment]
Technical ticket. Moving to PO review.

**Comment by JLWade** [comment]
going to leave in PO review until after meeting with DES team tomorrow in case there is any feedback to incorporate.

**Comment by JLWade** [comment]
Moving to done - there may be some changes once designs and wireframes are finalized and feedback like using ParkID instead of ORCS for aerogeneration, but these changes to the data model can be incorporated into development tickets.
