### ISSUE TITLE
UI - remove leading zeros from protected area IDs

### ISSUE THREAD

**Issue by janemoxd** [bcgov/parks-data-register#334]
We do not need to display leading zeros as a part of our IDs. These should be removed from the UIs.

e.g., Arrow Lakes Park ID can be displayed as 308 (instead of 0308 as we currently display it).

### AC:
- Leading zeros are not displayed as part of the protected area ID in page titles.
- Leading zeros are not displayed as part of the protected area ID on search results.
- Leading zeros are not displayed as part of the protected area ID anywhere else (?) they are shown on the admin site.

### Notes:
After conversations with Glenna and Rob, it become clear that leading zeros should not be displayed. 

**Glenna:** They don’t perform any function, but they are displayed in PAR. A holdover from the past. 
**Mark:** Only a display thing, leading zeros are not captured in the database. 
**Rob:** I personally don't see the need to display the leading zeros - they serve no purpose, as far as I can see.  I think they were only there because they were traditionally a portion/component of a larger code that had a very specific number of characters.  I have never displayed them with anything I've set up and they're not included in the CMS and I don't think it serves a purpose at this point.  I would be happy to see them removed.
Decision: Do not display leading zeros. Created ticket to remove them from Protected Areas.

**Comment by janemoxd** [comment]
@JLWade Can you please review this ticket and confirm that you are OK with this decision?

**Comment by janemoxd** [comment]
as per Jess on ticket #238, removal of leading zeros is approved but not urgent

**Comment by cameronpettit** [comment]
Addressed in https://github.com/bcgov/parks-data-register/pull/539
