### ISSUE TITLE
[M] Determine how to create audit trail and change log

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#34]
This spike is to investigate how best to create an audit log and a change log within the data register in order to track any change to the data. 

Audit log is meant to track who, what, and when data changes in detail. 
Change log is less granular and shows major name changes and times - this is the log that would be surfaced to the sysadmin user and some of this information may be surfaced to api subscribers. 

Acceptance Criteria:
- determine best approach for tracking change and audit data
- relate this approach to data model
- internal documentation here: https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Park+Names
   - once implemented document within README

Notes:
- relates to #33

**Comment by marklise** [comment]
Approach: Use the data model in PR https://github.com/bcgov/parks-data-register/pull/65.  DyanmoDB streams will need to be implemented in order to capture the pre/post operations into the Audit table.  See https://github.com/bcgov/parks-reso-api/pull/251 for example.
