### ISSUE TITLE
DR -> Missing the feature to view Change log items in detailed view.

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#345]
Scenario:
* Navigate to the DR on TEST environment
* Navigate to the Change log page
* Try to click on one of the data lines on the Change log to view the details. 

Expected:
Refer to the requirements. 
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=2575%3A3122&mode=design&t=hPnJvmWpybMkVj1g-1

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/50789261-360f-403b-9f1b-7217d35cee6c)

Issue:
* The data rows aren't clickable.

**Comment by JLWade** [comment]
Moving into current sprint as row should direct user to the view details page for that item. ie. park name is changed and listed in change log, I can click that row and it takes me to the park detail page.

**Comment by manuji** [comment]
Tested on TEST: Passed
* Verified that this issue has been fixed. 
* Passing to PO review.

**Comment by JLWade** [comment]
wrking - moving to done
