### ISSUE TITLE
DR-> Change log shows incorrect "Date of change" information

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#349]
Scenario:
* Navigate to the DR on TEST environment: https://test-data.bcparks.ca/admin/
* Navigate Protected areas page.
* Select any park and do a major change
* Navigate to the Change log page
* Check if you can see the Major change you did and verify the details displayed on the search table is correct.

Issue:
* The date displayed for the "DATE OF CHANGE" is incorrect. 

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/bc07f43d-3585-483e-baf8-6803f4a7eead)

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/bf4591a2-e19a-4ad6-bf59-541af8fa68de)

**Comment by JLWade** [comment]
this is high priority to resolve - moving into current sprint

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed.
