### ISSUE TITLE
[L] PIA and STRA

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#36]
Get PIA and STRA submitted for park data register project. 

**Acceptance Criteria:**
- PIA written and submitted - documented and saved in relevant folder
- STRA written and submitted - documented and saved in relevant folder

**Notes**
- approvals will likely take months so will be outside of the scope of this ticket

**Comment by JLWade** [comment]
PIA already returned and signed

**Comment by JLWade** [comment]
@JLWade  zap scans have been added - add to STRA

**Comment by JLWade** [comment]
Moving to done
