### ISSUE TITLE
[S] DR-> Incorrect help text displayed for "Display name" field

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#362]
Scenario:
* Navigate to the data register on TEST environment: https://test-data.bcparks.ca/admin/protected-areas
* Navigate to either major edit or Minor edit page of a aprk
* Select the checkbox to add a Display name. 
* Check the help text displayed for the field. 

Expected:
* The help text should read "Add a display name if the name that should be displayed on public facing materials is different from the legal name."

Issue:
* The help text displayed explains something that cannot be done as we have validation in place. 

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/add1dc7d-0eda-442d-a094-7dfded9f17ca)

**Comment by manuji** [comment]
FYI @janemoxd , reminder to update the Figma.

**Comment by cameronpettit** [comment]
Fixed in https://github.com/bcgov/parks-data-register/pull/436

**Comment by jpeersoxd** [comment]
Tested on TEST. Issue resolved. Moving to Done as this was internally reported.
