### ISSUE TITLE
Library: Define typography

### ISSUE THREAD

**Issue by janemoxd** [bcgov/parks-data-register#375]
Typography scale, sizes, colours need to be defined and added to design library.

Refer to:
BC Parks website in-use library
[BC Gov design tokens](https://www.figma.com/file/vZA3PwrZkHig1PwFjwm15J/B.C.-Design-Tokens-(v2.0.1)-(Community)?type=design&node-id=1%3A229&mode=design&t=djttqLQXf8XZbjUa-1)

Note:
It's likely that the BC Parks website in-use library typography scale will be applicable to the admin tools as well. Need to check this against what's in use to make sure it will make sense. And also check against the gov typography scale - may be that this is the one we should move forward with. To be discussed.

**Comment by Coneymaroney** [comment]
We are working on this iteratively as we go through the components and compare them with what we have in the admin tools. A continual work in progress.
