### ISSUE TITLE
Research for data register / data strategy

### ISSUE THREAD

**Issue by janemoxd** [bcgov/parks-data-register#380]
Research to decide what will be next to pull into the data register.

This research encompasses some strategic questions like:

- What will the architecture of the data register(s) look like?
- What data sets should be pulled into data register(s)?
- What is the purpose of the major data systems at BC Parks. 

Notes:
[See the data register research plan](https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/Design/Data%20register/data%20register%20phase%202%20research%20plan.docx?d=wac9e2c99ccdb485c882c5dcf32e2fb82&csf=1&web=1&e=BXtXpe).
[See the in progress report on this research](https://bcgov.sharepoint.com/:p:/r/teams/031072/Shared%20Documents/Design/Data%20register/Data%20register%20phase%202%20research%20findings%20-%20JM%20-%20V1.0.pptx?d=w075efe9bf2ca4f17b79f4f5799e26164&csf=1&web=1&e=9bhlc4).

**Comment by Dianadec** [comment]
@janemoxd we marked this as done during Sprint Planning but @meyerdarcie  will follow up to see if we need to generate other tickets to capture other related work depending on the progress.
