### ISSUE TITLE
[S] Add BC Parks bootstrap theme

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#39]
This ticket is to create the look and feel for the parks data register.

When user logs in through #24 they will see the usual header, footer, logo, colors, and fonts of the bc parks apps.

**Acceptance Criteria:**
- bootstrap theme is updated to use latest/correct BC Gov colours (talk to Harry)
- latest version of gov bootstrap with bc parks theme is added to project

**Notes:**
- https://github.com/digitalspace/bcparks-bootstrap-theme
- relates to front end view of this in #24

**Comment by manuji** [comment]
Blocked by https://github.com/bcgov/parks-data-register/issues/35

**Comment by JLWade** [comment]
moving to done as look and feel with bootstrap is up
