### ISSUE TITLE
Organize Figma - break A&R down into sub-pages related to specific topics

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#390]
As per a Feb 2024 retrospective action item, it was suggested to organize figma with specific topics rather than things in one long list on one big figma board. 

## Acceptance Criteria
- [ ] Review current Figma organization of A&R
- [ ] Create sub-pages related to specific topics (ask team if unsure how to split it up)
- [ ] Copy and paste figma designs into the sub-pages
- [ ] Throughout this process, circulate with team for feedback to see if figma organization is helpful to move forward

## Notes
https://www.figma.com/file/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?type=design&node-id=559-3339&mode=design&t=ImjRXYkTRTvCLiFH-0

**Comment by Dianadec** [comment]
@marklise do you have a link to another team's example of what you are expecting for this?

**Comment by JLWade** [comment]
prototype was working and looking good - moving to done
