### ISSUE TITLE
Google map not working on hack-map

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#393]
**Describe the bug**
The trip planning map on the github.io page is not displaying correctly or allowing search. 

**To Reproduce**
1. Go to https://bcgov.github.io/bcparks/map
2. scroll down to map and notice "this page cant load google maps" error
3. try searching for a location
4. See error in search

**Expected behavior**
Search and map works as expected

**Comment by marklise** [comment]
I think we need to make sure the Google API key has not been removed/deleted. @JLWade are you able to contact the people we got it from originally?

**Comment by marklise** [comment]
Billing issue - blocked until it gets resolved on the account.

**Comment by JLWade** [comment]
now working - moving to done
