### ISSUE TITLE
[M] Make a Minor Edit to a Site with an Established Status

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#398]
#### Description:

As a BC Parks Admin user, I would like to make a minor edit to a site that has an established status so that it can be up-to-date.

#### Acceptance Criteria:

Given that I am a BC Parks Admin User
When I click the edit button on a Site that has an Established status,
then I see a dropdown with different edit options: `Minor edit`, `Legal name`, `Repeal`

Given that I am a BC Parks Admin User
When I click the Minor edit button in the dropdown
then I am taken to the edit view for making a minor edit

Given that I am a BC Parks Admin User
When I make edits to the form and complete all valid fields
then I can save my changes when the Save button is enabled.

Given that I am a BC Parks Admin User
When I click the Save button after editing a form
then I see a toast message displayed (either success or error toast)

Given that I am a BC Parks Admin User
When I click on the Details button after making changes
Then I see a warning displayed, then I am taken back to the _2.0 View Site Record_ page 

#### Development Checklist:

- [x] The details button takes user back to the _2.0 View Site Record screen.
- - [x] Upon clicking the details button, if changes have been made, display a warning.
- [x] This form is the same as the Minor Edits form for Protected Areas. All design and behaviours should be duplicated from that page.
- [x] Current legal name checkbox:
- - [x] If the Site's `Legal Name` and `Display Name` are currently the same, default this check box to checked, and don't display `Display Name` field.
- - [x] If the Site's `Legal Name` and `Display Name` are different, default this box to unchecked, and display the `Display Name` field populated with the current `Display Name`.

**Wireframe(s)**:
2.1.1.1a Make Minor Edits to Site (Established Status)
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3842%3A13558&mode=design&t=zk1gqGE2sJkNs6Ea-1

- Clickable prototype for Edit dropdown: https://www.figma.com/proto/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=4361-116757&t=KRBDpucZHEPKgzYq-0&scaling=min-zoom&page-id=4361%3A116641&starting-point-node-id=4361%3A116757

**Workflows:**
'Process Flow - Make Minor Edit to Site':
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2480&mode=design&t=zk1gqGE2sJkNs6Ea-1

'User Flow - Site Name - View, Edit
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2585&mode=design&t=zk1gqGE2sJkNs6Ea-1

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- This piece was broken out from the original ticket: https://github.com/bcgov/parks-data-register/issues/124

#### Dependencies

- Blocked by
- Blocking

**Comment by Dianadec** [comment]
I have updated the ticket description based on the edit dropdown solution update

**Comment by jpeersoxd** [comment]
Tested on TEST. No issues found. Moving to PO Review.

**Comment by JLWade** [comment]
working as expected - moving to done
