### ISSUE TITLE
[M] Setup keycloak with new client

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#40]
Add new client to our BC Parks Service Transformation keycloak realm and set up normal configurations for idir and sysadmin role.

Acceptance Criteria:
- client for parks-data-register is added to realm, visible in redhat under clients
- sysadmin role exists for this client (read/write), this role can be added to users

Notes:
#24 is front end user portion of logging in via this work

**Comment by marklise** [comment]
KC done in dev/test/prod.  We will need to revisit once we have AWS URL's and vanity URL's to point to.

**Comment by manuji** [comment]
Tested on TEST and PROD: **Passed**

* Verified that both TEST and PROD key cloak has the client role "data-register" with the role "sysadmin".


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/cccfc7f3-4f96-4498-a12b-ada843a87015)

**Comment by JLWade** [comment]
viewed in keycloak - moving to done
