### ISSUE TITLE
[L] Change Legal Name of Site

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#401]
#### Description:

As a BC Parks Admin user, I would like to change the legal name of a Site so that it is up-to-date.

This is the form users will see when, in a Site details page, they click the Edit button and in the dropdown select `Legal Name`.

#### Acceptance Criteria:

Given that I am a BC Parks Admin User
When I update the legal name for a site and click Save Changes
then the new name will replace the current name AND the name currently in use and all its associated data will automatically be placed under historical names.

#### Development Checklist:

- [x] This form and all behaviours are the same as for Protected Areas. Form will be blank by default
- [ ] For this form, Display Name checkbox will be checked by default, as most Sites will not have a separate display name.
- [ ] ...

**Wireframe(s)**:
2.1.1.2 Change Legal Name of Site
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3842%3A13916&mode=design&t=Wja03WX4eAWFIV6w-1

**Workflows:**
'Process Flow - Change Legal Name of Site':
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2422&mode=design&t=Wja03WX4eAWFIV6w-1

'User Flow - Site Name - View, Edit
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2585&mode=design&t=zk1gqGE2sJkNs6Ea-1

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- This piece was broken out from the original ticket: https://github.com/bcgov/parks-data-register/issues/124

#### Dependencies

- Blocked by
- Blocking

**Comment by Dianadec** [comment]
I have updated the ticket description based on the edit dropdown solution update

**Comment by cameronpettit** [comment]
Development Checklist:
> For this form, Display Name checkbox will be checked by default, as most Sites will not have a separate display name.

Why? Why not just follow the same logic as the protected-area? If the site has a different legal and display name, show the display field, if theyre the same, hide the field.

**Comment by jpeersoxd** [comment]
Tested on TEST. No issues found. Moving to PO Review.

**Comment by JLWade** [comment]
working as expected - moving to done
