### ISSUE TITLE
[M] Repeal Site

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#402]
#### Description:

As a BC Parks Admin user, I would like to repeal a Site so that its status is no longer listed as established.

This is the form users will see when, in a Site details page, they click the Edit button and in the dropdown select `Repeal`.

#### Acceptance Criteria:

Given that I am a BC Parks Admin User
When I choose an effective date in the Repeal Site screen and click Save Changes
then the status of the Site will be set to repealed

#### Development Checklist:

- [x] Ensure data is being transmitted properly to the API
- [x] Properties being changed need to map to the model appropriately
- [x] System-generated date updated need to be set as part of the call (not from the front end)

**Wireframe(s)**:
2.1.1.3 Repeal Site
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=4495%3A10450&mode=design&t=Gke5CBNRlpx961PR-1

**Workflows:**
'Process Flow - Repeal Site':
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2364&mode=design&t=Wja03WX4eAWFIV6w-1
'Process flow - Edit Repealed Site':
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2537&mode=design&t=Wja03WX4eAWFIV6w-1

'User Flow - Site Name - View, Edit
https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3898%3A2585&mode=design&t=zk1gqGE2sJkNs6Ea-1

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- This piece was broken out from the original ticket: https://github.com/bcgov/parks-data-register/issues/124
- Related to #326 

#### Dependencies

- Blocked by
- Blocking

**Comment by jpeersoxd** [comment]
Tested on TEST. No issues found. Moving to PO Review.

**Comment by JLWade** [comment]
working as expected - moving to done
