### ISSUE TITLE
When PO moves something to Done column it closes github issue

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#403]
As part of the Osprey dev team, I want to easily mark issues as closed when they are complete so that it is clear what is an open or closed issue.

In our project board (https://github.com/orgs/bcgov/projects/49/views/1) the last step is for PO to move a github issue into the done status/column. When this happens the issue remains open even though it is complete. This ticket is to create an action that automatically moves an issue in done to closed so that we dont have a bunch of done open issues.

## Acceptance Criteria
Given I am the PO
When I move something to done in our sprint board
Then the issue is marked as closed.

**Comment by Dianadec** [comment]
@JLWade I believe I found a solution to this using gh project workflows. A slight change to your flow would be: Upon approving a ticket, use the 'Close' button. You can also add a comment to provide any feedback to the team then the button says "Close with comment". Using the workflow I've setup, this will automatically send the ticket to the "Done" column/status.


![Image](https://github.com/bcgov/parks-data-register/assets/35785153/fe41a9ae-1a69-4ce4-9486-e3e00e731f7a)

**Comment by JLWade** [comment]
nice! so sounds like I can move this one to done!
