### ISSUE TITLE
Update Designs with different edit functionality

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#411]
**Context:** Sites implementation tickets have surfaced complexities with the current designs and workflows, specifically with the `Edit Record` page, and the almost identical `minor edit` and `legal name change` pages.
 
**Solution change:** Rather than having the [Edit Record](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=948%3A7065&mode=design&t=cys2UTkwRNZRGm4D-1) page, the '[View Site Record](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3299%3A5591&mode=design&t=cys2UTkwRNZRGm4D-1)` page should have each of the edit options as a drop-down edit list. Upon clicking a dropdown list item, user will be taken to the associated Edit page type (eg: Minor edits, Legal name change, or Repeal status). 
 
**Rationale:**  We have more things to add to this application, and the longer we wait to make changes like this, the bigger the changes will become. The updated edit flow proposed will be better for implementation sustainability and will still meet the needs of users.

## Acceptance Criteria
- [x] Update wireframes accordingly: '[View Site Record](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3299%3A5591&mode=design&t=cys2UTkwRNZRGm4D-1)` page should have each of the edit options as a drop-down edit list. Upon clicking a dropdown list item, user will be taken to the associated Edit page type (eg: Minor edits, Legal name change, or Repeal status). 
  - Given that I am a BC Parks admin user
When I click the edit button on a Sites record view page
then a dropdown appears with 3 edit options: Make a minor edit, Change legal name, Set status to repealed
- [x] Update wireframes and flow for the edit button within the Search Table: '[Search](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=3246%3A2881&mode=design&t=dhOrn6a1UUdAx4Im-1)'. Page should follow the same flow, where user clicks through to record and then to the edit page.

**Comment by JLWade** [comment]
looks good moving to done
