### ISSUE TITLE
[M] Update CI/CD pipeline

### ISSUE THREAD

**Issue by marklise** [bcgov/parks-data-register#444]
Business value: makes development more efficient and less errors coming up with sonar cloud

- Sonarcloud settings can be updated
- codeql setup and configure
- trivy setup and configure

**Examples to look at:**
- https://github.com/bcgov-nr/action-test-and-analyse
- https://github.com/bcgov/quickstart-openshift/blob/main/.github/workflows/analysis.yml
- https://github.com/bcgov/quickstart-openshift

#### Acceptance Criteria:

- [ ] only relevant sonarcloud warnings are displayed

#### Development Checklist:

- [ ] codeql is set up and configured correctly
  - [ ] DUP
  - [ ] A&R
  - [ ] DR
- [ ] trivy is set up and configured correctly
  - [ ] DUP
  - [ ] A&R
  - [ ] DR 

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- no code to test - can move from in progress to done once complete
-

**Comment by marklise** [comment]
@JLWade @Dianadec coming from NRIDS FYI

**Comment by JLWade** [comment]
for QA - smoke test

**Comment by Dianadec** [comment]
todo: find out reasoning behind needing to do this - bcgov connect cc @meyerdarcie . eg: do we need sonarcloud??
Contact: ps team
context: mandated by nrids

**Comment by danieltruong** [comment]
Closing this ticket. Deleting SonarCloud and moving to CodeQL.

**Comment by Dianadec** [comment]
Pulled back in to go through these points:
codeql setup and configure
trivy setup and configure
