### ISSUE TITLE
Prototype Backcountry Booking - TO BE BROKEN OUT AFTER MAPPING SESSION

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#449]
#### Description:

As a backcountry camper, I want to be able to reserve a backcountry spot so that I can plan my trip and feel confident I have a place to stay.

Questions for prototype:
- what should be our focus area? 
- think about what patterns are new and what need to be designed? (ie. payment, calendar bookings, maps, contact forms)
- how can we break out this ticket to show different pieces of the prototype?
  - designs
  - infrastructure set up
  - components
  - 3 epics: design, FE, BE
  - workflows:
    - workflow to include all possible cases of things happening
    - business rules - look at things that exist in current system for rules
    - what pain points do people experience?
  - create super drafty wireframes in our style, quick prototype, pull biz rules out of that, devs go into backend.

#### Acceptance Criteria:

Given
When
Then 

Given
When
Then

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Ideas discussed during Refinement:
3 epics: Design, Front end (dependent on design), back end (API - same as DR) (can be worked on during designs)
Need workflow at least before designs or backend API.
- workflow to include all possible cases of things happening
- business rules - look at things that exist in current system for rules - pull from camis confluence.

Keeping in mind - don't just redo Camis - what pain points do people experience?

other ideas - try something different:
- create super drafty wireframes in our style, quick prototype, pull biz rules out of that, devs go into backend.

**Comment by meyerdarcie** [comment]
@Dianadec closing this ticket as we've now broken out our backcountry prototype.
