### ISSUE TITLE
Filter Change Log

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#45]
As a...
I need...
So that...

Acceptance Criteria:

Notes:

**Comment by LindsayMacfarlane** [comment]
@Dianadec @davidclaveau - do either of you have background on this ticket? Recommendations to keep or close?

**Comment by davidclaveau** [comment]
@LindsayMacfarlane similar to the Search Change Log ticket, I think this is complete as there are a couple filters in the Change Log; could be another duplicate or maybe there were more filters to be implemented. Might need someone else to confirm if that's true or not 😅

**Comment by LindsayMacfarlane** [comment]
Closing as most likely a duplicate and no longer needed.
