### ISSUE TITLE
Search Change Log

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#46]
As a...
I need...
So that...

Acceptance Criteria:

Notes:

**Comment by LindsayMacfarlane** [comment]
@Dianadec @davidclaveau - do either of you have background on this ticket? Recommendations to keep or close?

**Comment by LindsayMacfarlane** [comment]
@davidclaveau - that helps a lot! Thank you!

**Comment by LindsayMacfarlane** [comment]
Closing this ticket as no longer needed.
