### ISSUE TITLE
DR-> The site name displayed on Protected area should be the legal name instead of the display name

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#461]
This is related to the Task ticket: https://github.com/bcgov/parks-data-register/issues/394

Scenario:
* Navigate to the DR on TEST environment
* Find a protected area with Sites.
* Check the Site name displayed. 

Expected:
* Should display the legal name of the Site on the View Protected area page.

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/499acf4b-64c4-45c7-b59c-327a20c96845)

Issue:
* The Site names displayed on the View protected area page is using the Display name instead of the Legal name.

https://github.com/bcgov/parks-data-register/assets/65190263/9427aca5-d595-489a-a76a-da2fdc1a8f1a

**Comment by JLWade** [comment]
I think we should change the UI specs on this and have it show display name here

**Comment by LindsayMacfarlane** [comment]
November 4, 2024 - took a look at this ticket this morning and unsure what exactly is needed. The UI in the top image differs from what has been implemented. @manuji - can I get you to take a look at this ticket and confirm if this ticket is done/still needed. 

cc @Dianadec

**Comment by manuji** [comment]
@LindsayMacfarlane , as per the @JLWade 's comment looks like we don't have to work on this ticket as it's okay to display the "Display name" on details page. I will close this ticket. Thank you.
