### ISSUE TITLE
[M] Flowchart for Payment Process

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#465]
#### Description:

This task is to map out the workflow as noted in #448, something like this: select an item --> click purchase -->payment form --> fill out payment info ---> pay --> success/confirmation of purchase

The AC of this ticket has changed significantly since its creation - we were set on using Bambora before, now we are advocating for the use of Stripe, we need a comparison between the two payment processing services.

#### Acceptance Criteria:
Given I'm a developer on Osprey
~~When I pick up the payment prototype ticket~~
~~Then I have documentation of the workflow to follow for the prototype~~
When I want a high level map of how Bambora and Stripe handle payments
I have documentation

Given I'm a business analyst
When I need a comparison between Bambora and Stripe payment processing
I have comparative documentation available

- [ ] work flows for common use cases are captured in fig jam (figma) or mural  - _where?_
  - [ ] Use cases for prototype:
    - [ ] happy path - success all is correct no errors
    - [ ] wrong info entered  (generic errors)
    - [ ] no credit available (error)
  - [x] available payment methods
    - [x] prerequisite information necessary 
    - [x] sensitive information obfuscation methods
    - [x] UI customizability

#### Development Checklist:

- [ ] use Fig Jam
- [ ] ...
- [ ] ...

#### Dependencies

- Blocking #448 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Check if we can use dds' fig jam account so we can have one fig jam thing per project (DUP, AR, etc).

**Comment by Dianadec** [comment]
@cameronpettit  could you update this ticket with the work that you actually did related to a flowchart??

**Comment by cameronpettit** [comment]
Figjam of flow can be found here https://www.figma.com/board/tIJR2X4iS3gEEUFFHejqpu/Payment-Service-Flowchart?node-id=23-1064&t=MaM7SYA6pV1jdDSq-0 (may need to request access).

Can re-open this ticket or link to it in the future.
