### ISSUE TITLE
[S] Update github.io project page - remove parks adventure mobile

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#466]
#### Description:

This ticket is to make a small update to the github.io project page.

#### Acceptance Criteria:
- [x] remove Parks Adventure Mobile project

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [x] Work is traceable in GitHub
  - [x] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
@manuji not sure if this goes to you for the same QA, but looks like it's live now! https://bcgov.github.io/bcparks/projects

cc // @JLWade in case it just moves to PO review or closed.

**Comment by manuji** [comment]
Tested on https://bcgov.github.io/bcparks/projects and verified that the above mentioned project has been removed. 
Passing to PO review.

**Comment by JLWade** [comment]
project removed as expected - moving to done
