### ISSUE TITLE
[L] Update Bootstrap Library to use Tokens

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#468]
#### Description:

The tokens have recently been completed and we now need to update the bootstrap library.

https://github.com/digitalspace/bcparks-bootstrap-theme

#### Acceptance Criteria:

- [ ] Bootstrap variables match the [token glossary](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary) 
- [ ] Font sizes and weights match [token glossary](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary) 
- [ ] Library uses standard bootstrap spacing 
- [ ] Admin specific components and overrides match what is in the [Admin Library Figma](https://www.figma.com/design/3Zthj9Ci5QoJOAz6p3TcLP/BC-Parks---Admin-Library?node-id=0%3A1&t=3xH52xVVVLaBTnsw-1)

#### Development Checklist:

- [ ] variables.scss is updated with token colour codes
- [ ] overrides.scss, fonts.scss, and additional.scss are reviewed to ensure they match the figma and token glossary guidelines

#### Dependencies

- Blocked by #314 , #375 
- Blocking #469 , [#335](https://github.com/bcgov/parks-data-register/issues/469), [#355](https://github.com/bcgov/parks-reso-admin/issues/355)

**Relevant documentation as reference**

[Tokens overview](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens#overview)
[Token glossary](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary) 

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* From a QA perspective no issues were found after this update on the UI. 
* I noticed some discrepancies compared to the design token glossary such as DR H1 tags uses a different fornt size than what is given on the glossary. 
* I highly recommend getting this ticket a pass from the Design expertise to confirm everything is as per the Design token glossary.

**Comment by manuji** [comment]
I will grab this back to report UI issues on DUP.

**Comment by manuji** [comment]
Tested o TEST DUP-Public: Pending

Given below are the UI issues I have noticed after updating with the new Bootstrap tokens.

1. The font and components on "Booking time" section looks smaller when compared to the rest of the content. 

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/727d7d27-a35d-4305-b749-cc37d80db534)

2. The font sie of the labels on visitor information form is small when compared to the rest of the content when set to 0.75rem


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/f8ba4dee-e0e9-48c7-8444-44424d44869a)



![Image](https://github.com/bcgov/parks-data-register/assets/65190263/181ebe39-a665-4310-893a-d4dd76513a73)

@meyerdarcie , @meredithom

**Comment by meredithom** [comment]
DUP Admin changes:

- Breadcrumb colour doesn't cover entire breadcrumb area.
- Cards not centered on home page
- Metrics page: too small of font for the date filters, should match other button
- FAQ page: title too small, remove bg colour 

DR and A&R changes have been added to their tickets: [#335](https://github.com/bcgov/bcparks-ar-admin/issues/335) and #469

**Comment by Dianadec** [comment]
Notes: will push this to PROD but will revisit token library about font sizes

**Comment by manuji** [comment]
@meredithom This is deployed to TEST and ready to review.

**Comment by manuji** [comment]
@meredithom , I verified all the issues you mentioned in the previous comment are fixed except for the last one about the FAQ page. Given below is how it looks with the background color. 



![Image](https://github.com/user-attachments/assets/ef3c5dd0-8c8d-40db-ad37-39862b4c2d6d)

Please let me know if this is expected or should the background color be "#fff"?

**Comment by meredithom** [comment]
Background should be #ffffff.

**Comment by manuji** [comment]
Moving this ticket back to To do column to fix the background color of the FAQ page on DUP-Admin.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed. 
* Passing to PO review.
