### ISSUE TITLE
[L] Update DR admin UI, tokens and admin library

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#469]
#### Description:

Updating data register admin to match the figma that has the admin library and design tokens applied.

#### Acceptance Criteria:
Data Register UI matches figma and uses the colours, fonts, sizes and styling from the Admin Library.

#### Development Checklist:

- [ ] Updated Bootstrap library is imported
- [ ] Components are updated to use bootstrap standard where possible 
- [ ] UI matches [DR Figma](https://www.figma.com/design/qdjegD6YHWZPlyFT8dGXvk/Data-Register?node-id=0%3A1&t=hZBJkwqxvHLzBdYx-1)

#### Dependencies

- Blocked by #468 , #315 
- Blocking

**Relevant documentation as reference**

[Tokens overview](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens#overview)
[Token glossary](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary)
[DR Figma](https://www.figma.com/design/qdjegD6YHWZPlyFT8dGXvk/Data-Register?node-id=0%3A1&t=hZBJkwqxvHLzBdYx-1)

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by meredithom** [comment]
Only colours, fonts, sizes and styling updated, components will need to be updated as necessary after the figma library is updated  [#315](https://github.com/bcgov/parks-data-register/issues/315)

**Comment by meredithom** [comment]
Some updates to be made before moving to prod:

- breadcrumbs missing background colour, should look like:
![Image](https://github.com/bcgov/parks-data-register/assets/15185966/dea4ca58-735b-4d62-9aed-882183bd4b9b)

- Cards aren't centered on the home page
- Text and spacing is off on the Protected Area page, should roughly match Figma:
https://www.figma.com/design/qdjegD6YHWZPlyFT8dGXvk/Data-Register?node-id=4917-13239&t=ohRxdEdKJNfNNXrX-1

**Comment by manuji** [comment]
@meredithom This is deployed to TEST and ready to review.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the issues mentioned have been fixed. 
* Did not verify against the figma as the updated are still in progress: https://github.com/bcgov/parks-data-register/issues/315
* Moving to PO review.

**Comment by meyerdarcie** [comment]
Moving this ticket to done - additional figma changes in #315
