### ISSUE TITLE
DR-> Legal name change confirmation summary shows a stray word "true" with no context.

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#471]
Scenario:
* Navigate to the DR on TEST environment.
* Select a park and make a legal name change. 
* Make sure to check the checkbox for "Legal name is the same as Display Name"
* Submit the changes and check the content given on the confirmation message. 

Issue:
* Display the word "true" on the summary/confirmation overlay, when the checkbox "Legal name is the same as Display Name" is selected, without much context to it. 

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/d000cf06-e42e-4d52-87cd-ad2146cbb49a)

Expected:
* If we decide to leave that information, then we need a title explaining what field that information is from. 
* Else, hide it from the summary.

**Comment by LindsayMacfarlane** [comment]
Tested on November 1, 2024: bug still experienced. Low priority for fixing; however, if the team is looking for something could be a good ticket to address.

**Comment by manuji** [comment]
Tested on [TEST](https://test-data.bcparks.ca/admin/): Passed
* Verified that this issue has been fixed. 
* Moving to Done.
