### ISSUE TITLE
Share Take-aways and learnings from Agile Unconference

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#472]
## Description
After attending the Agile Open Canada 2024 Unconference, Kavi will share her takeaways with Jess about what she learned.

## Acceptance Criteria
- [x] A document/template of choice is prepared to demonstrate the learnings
  - [x] If a document is created, then share with her
- [ ] ~~Not to take longer than a couple hours~~
- [x] Set up a meeting with Jess in her calendar
  - [ ] ~~Update the meeting with an agenda to help keep meeting on track~~
- [x] Create a GH ticket
  - [x] Update the ticket with content

### Dependencies
Blocked by:
- [x] Attending the event

## Definition of Ready
- [x] Acceptance criteria are included
- [x] Wireframes are included (if applicable)
- [x] Design / Solution is accepted by Product Owner (if applicable)
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

### In progress
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to 

### PO Review
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

**Comment by kgorana** [comment]
@JLWade  I updated the ticket with content and it is ready to be reviewed by you - if everything seems fine, I can move it to "in progress" after.

**Comment by JLWade** [comment]
perfect! thanks Kavi!

**Comment by JLWade** [comment]
great presentation - moving to done
