### ISSUE TITLE
[M] Setup Code Documentation Standards for Data Register

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#48]
This ticket is to update our documentation when we begin this project, this includes updating README's in repo's for data register project and updating our github.io page.

Should be added/updated to api and admin/frontend repo's and both should be as up to date as possible (will likely need to update as we build out).

**Acceptance Criteria:**

- update README’s to ensure everything is current
- add a code of conduct to all repo’s
   - see here for example: https://docs.developer.gov.bc.ca/required-pages-for-github-repository/ or https://github.com/bcgov/parks-reso-public/blob/main/CODEOFCONDUCT.md
- add contribution guidelines to all repo’s 
   - see here for example: https://docs.developer.gov.bc.ca/required-pages-for-github-repository/ or https://bcgov.github.io/bcparks/collaborate
- add project to github.io page:  https://bcgov.github.io/bcparks/projects

**Comment by JLWade** [comment]
@meredithom - are you able to add a lifecycle badge to our repo? github suggested it and I think that was one of the previous requirements. If it's a lot of work we can make a new ticket

**Comment by manuji** [comment]
Tested and verified that this task has been completed. Ready for PO review. ✅

**Comment by JLWade** [comment]
looks good - moving to done
