### ISSUE TITLE
[L] Payment options analysis & documentation based on prototypes

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#482]
#### Description:
We need to document a simple options analysis (pros/cons; rationale; implications) to back up decision making around payment options. Will be blocked by 2 prototype tickets, and likely same person doing it

#### Acceptance Criteria:

- [ ] Document outlining pros/cons/implications of payment options, informed by bambora and stripe payment prototypes

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by #479 and #448 
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by cameronpettit** [comment]
A comparison between Bambora and Stripe is part of the Figjam file where the payment flows were documented as part of #465. Refer to [this comment](https://github.com/bcgov/parks-data-register/issues/465#issuecomment-2168719693) for Figjam link.

I've also attached a partially attempted/filled out PIA form. It is super high level of detail (and incomplete) but should probably be done in tandem with someone who will be filling it out for real - I'm happy to work with whomever that may be. Basically - as far as PI is considered when discussing Bambora vs Stripe, both options are going to be very similar in the major points of the PIA - namely the types of PI being collected and the assumptions of risks that go along with them. Bambora is much more difficult to get a clear answer on points of their data storage methodologies, their service providers and the location of their servers. 

[PIA_PRDT.docx](https://github.com/user-attachments/files/15843595/PIA_PRDT.docx)

When it comes to the backcountry reservation system, the region where Osprey's responsibilities re: PCI compliance lie does not really overlap with either Bambora and Stripe. It is our responsibility to remain PCI compliant while collecting financial and personal information from our users, and that responsibility does not change much whether or not Bambora or Stripe is used.

My job as a software developer and consultant is to provide my best recommendations from a software development standpoint, and from that standpoint, Stripe is a clear, no-contest winner when it comes to choosing a payment processing service. Their modern administrative portal, extensive developer resources and implementation examples, and proven real-world use cases give me confidence that Stripe would effectively meet (and exceed) the payment service needs Osprey has for this new backcountry payment system. Bambora could be made to meet these needs too, but doesn't seem to hold the same pedigree necessary for the size and importance of the payment handling demand that BC Parks has. For this product to succeed, it will need to grow iteratively, so lets iterate using the modularity and scalability of a Stripe foundation with assurance it will grow with us.

Some things that are out of the scope of my comparison are any considerations that are not explicitly technical, for example: cost, contracts, and non-technical PIA/STRA considerations. I will say that I foresee developer implementation time being a huge upcoming investment that can be lessened/hastened by choosing a payment platform that is easy and versatile for developers to leverage.
