### ISSUE TITLE
PRDT: Create repositories

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#494]
#### Description:

See repo decision thread: https://teams.microsoft.com/l/message/19:163facd69a2e4fe1a14eac3ae95fb3c4@thread.tacv2/1717526830522?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1717526830522&teamName=External%3A%20Team%20Osprey&channelName=Dev%20Chat&createdTime=1717526830522

#### Acceptance Criteria:
Created 3 repos in github: 
reserve-rec-api
reserve-rec-admin
reserve-rec-public

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
done: https://github.com/bcgov/reserve-rec-api
https://github.com/bcgov/reserve-rec-admin
https://github.com/bcgov/reserve-rec-public

**Comment by meyerdarcie** [comment]
Repos created, moving to done.
