### ISSUE TITLE
[S] Improve email sanitization prior to bulk GCN jobs

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/parks-data-register#498]
Recently we had a GCN bulk job failure where no reminder emails for June 6th 2024 (reminder sent on June 5th, 2024 @4pm) were sent as part of the `sendReminder` job. The job failed due to an invalid email address (younwoo0103@naver..com) making its way past our FE regex filter. The invalid email caused the entire job to fail, after which we have no retry logic in place. 

We do save metadata from failed jobs to our database and we were able to determine the exact email that caused the problem from the metadata. The email address was amended and the `sendReminder` lambda was rerun, resulting in a successful bulk email job with GCN.

This bug is to address this shortcoming where some invalid email addresses still make it passed our FE regex filter. We attempted this fix once before since GCN has extremely poor error handling logic and there is little other way to ensure GCN will accept an email before sending it off to the bulk job. We'll never know what GCN considers an invalid email so we can't exactly match their expectations. 

Proposed fix:

- update the regex to exclude the case where the email is invalid in the case above (`..com`, two dots)
- clarify the bulk email job logging and reveal errors at the `logger.info()` level
- investigate/implement a back-end approach to sanitizing emails, drop invalid emails before they reach the bulk job, remove problematic entries and retry the job upon failure if possible. 

**To Reproduce**
1. Go to DUP FE and attempt to reserve a pass; get to the contact information screen
2. Try to enter an invalid email in the email field, most of the time you will be denied but not in the `..com` case.
3. Completing the booking should cause a fatal GCN error in the logs

**Expected behavior**
Users should not be able to enter an invalid email, and if they do it should not cause such catastrophic GCN issues...

**Comment by Dianadec** [comment]
@meyerdarcie  fyi at standup Cam explained this bug he found. It's in the current sprint but doesn't necessarily need to be done this sprint.

**Comment by manuji** [comment]
While testing I encountered this duplicate error message with the email address "very.unusual..unusual//.@example.c/"

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/3c85ee42-0806-4b33-bd43-acfd123f1a2f)

Scenario:
* First enter the email address "very.unusual..unusual//.@example.c/" to the first email field.
* Then re enter the same email address to the confirm email address field, when you finish typing a duplicate error will be added to the first field.

**Comment by Dianadec** [comment]
@marklise  are you able to look at this again (see manuji's comments)

**Comment by marklise** [comment]
@manuji @Dianadec  I don't think this should be blocking release to prod as this is just a UI issue and no longer a data quality issue once the fix is put into place.  There are several other patterns that the current form validator does not account for, and the need to fix this quickly was prioritized over a 100% coverage of email checking.

**Comment by manuji** [comment]
Noted with thanks @marklise . Passing this ticket to PO review.

**Comment by meyerdarcie** [comment]
Moving to done.
