### ISSUE TITLE
[M] DR: Add new parks and conservancies to data register

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#505]
#### Description:
This ticket is to update the data register with 2 new parks and 10 new conservancies (ORCS numbers already identified). 

June 20, 2024:
- Klinse-za/Twin Sisters Park (9956) - COMPLETE
- Klinse-za/Twins Sisters Protected Area (9958)

June 26th, 2024
- 10 Claypquot Sound conservancies linked in this document: https://bcgov.sharepoint.com/:w:/r/teams/08548/Shared%20Documents/General/1.%20Project%20Documentation/1.%20Data%20Register/Clayoquot%20Conservancy%20Names,Pronunciations%20and%20Meanings.docx?d=w1a77ae757e87420d9f4d5b3887bdfa80&csf=1&web=1&e=0BXtWd

#### Acceptance Criteria:

- [ ] 2 new parks added and visible on data register, using BC Sans and Indigenous characters
- [ ] 10 new conservancies added and visible on data register, using BC Sans and Indigenous characters

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- / #

**Comment by meyerdarcie** [comment]
Added document to teams listing the new conservancies: https://bcgov.sharepoint.com/:w:/r/teams/08548/Shared%20Documents/General/1.%20Project%20Documentation/1.%20Data%20Register/Clayoquot%20Conservancy%20Names,Pronunciations%20and%20Meanings.docx?d=w93489f4de6c34e74b3fed666b978b181&csf=1&web=1&e=I8dfye

**Comment by Dianadec** [comment]
@meyerdarcie  Did we find out about the characters?

**Comment by cameronpettit** [comment]
@meyerdarcie @Dianadec there is missing information we need before these items are added to the database.

- `status` (is the protected area established or repealed, I presume all of them will be established but we still need to know)
- `effectiveDate` (when the protected area was established/repealed)
- `displayName` and `legalName` must be provided with the correct UTF-8 encoded characters - providing an image of the name is not good enough for us, we don't decide which characters are used to represent those in the image. 

![Image](https://github.com/bcgov/parks-data-register/assets/71421099/08742ede-dc77-4b5b-b6d3-dc14d23ed8fc)

I've provided an Excel spreadsheet highlighting the missing information we need to proceed, using Neğiƛ/Nekite Estuary Conservancy as an example. Whomever is requesting these additions to the registry - please get them to complete the highlighted cells.

[PDR-505.xlsx](https://github.com/user-attachments/files/16183305/PDR-505.xlsx)

In the future, when we get requests of this kind, please have the requesters complete the highlighted fields this Excel doc as a template to give us the minimum viable data before proceeding.

As a side note, this is a perfect example of why we should have built the functionality for administrators to add their own data to the registry themselves in the first place - neither of you were on the team yet though, so you both are exempt from my 'I told you so' wrath 👼 

Moving to blocked until this is completed.

**Comment by Dianadec** [comment]
Thanks Cam! Darcie will be updating the spreadsheet today.

**Comment by meyerdarcie** [comment]
@cameronpettit - updated spreadsheet available here: https://bcgov.sharepoint.com/:x:/r/teams/08548/Shared%20Documents/General/1.%20Project%20Documentation/1.%20Data%20Register/PDR-505%20-%20new%20protected%20area%20template.xlsx?d=wc8947ba673b14174bec67a085fc003b0&csf=1&web=1&e=rqOm7A

FYI that Klinse-za/Twin Sisters Park has already been updated as Glenna was able to action that herself. She will also add search terms as needed as she is also able to update that.

**Comment by cameronpettit** [comment]
@meyerdarcie @manuji this change is completed in PROD.

**Comment by manuji** [comment]
Tested on PROD: Pending

@cameronpettit I am seeing a discrepancy in PK given on the excel sheet and the DynamoDB (eg: Kiišḥniqʷus Conservancy) for several parks. is this something I have to worry about?  



https://github.com/user-attachments/assets/4523f1ce-8f29-426d-a597-f7430026fbda

**Comment by cameronpettit** [comment]
ugh good catch @manuji. Looks like when the source excel was filled out, the rows were shuffled, leading to mismatched orcs vs displayIds. They're supposed to be the same. I'll have to fix this manually.

**Comment by cameronpettit** [comment]
@manuji @meyerdarcie The information currently in PROD matches what was originally listed in the word documents - so I think what is in PROD is actually already correct. Not sure why pk/displayId didn't match in the Excel document, but they've been updated to match now.

**Comment by manuji** [comment]
Thanks @cameronpettit , I will check the DynamoDB and verify.

**Comment by manuji** [comment]
Hi @cameronpettit verified that the PK and DisplayID are matching when compared to the word doc. One park on the word doc is not on both DynamoDB and the PROD DR Admin with the Orcs: 9973. I think we missed that one park.  
<img width="1041" alt="Screenshot 2024-07-30 at 12 47 19 PM" src="https://github.com/user-attachments/assets/36b48845-75f4-479c-ad51-1adff8d7b1f3">

**Comment by cameronpettit** [comment]
@meyerdarcie  looks like we missed 1 park that will need to be UTF-8 encoded. https://bcgov.sharepoint.com/:x:/r/teams/08548/_layouts/15/Doc.aspx?sourcedoc=%7BC8947BA6-73B1-4174-BEC6-7A085FC003B0%7D&file=PDR-505%20-%20new%20protected%20area%20template.xlsx&action=default&mobileredirect=true

**Comment by meyerdarcie** [comment]
@cameronpettit sheet is now updated, thanks.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that the last items has been added to the Data register as well
* Passing to PO review

**Comment by meyerdarcie** [comment]
Looks good, moving to done.
