### ISSUE TITLE
Create Park Name metadata record

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-data-register#507]
## Description:
We need to create a metadata record in BCDC so that it helps us move to the next step of ticket #123.

## Acceptance Criteria:
- @JLWade will be ready to publish the metadata record as a DRAFT for the team to review it this week or next week and start with the ODL checklist after
- all the interested parties agree that the first draft is good and if anything changes, they let the Data Custodian (or the Editor @JLWade) know

## Development Checklist:
- [x] Editor creates a new metadata record in 'Draft' status - responsible: @JLWade - deadline: 2024-06-06
  - [x] Complete the [form](https://bcgov.sharepoint.com/:w:/r/teams/08548-KaviJessAshley1on1s/Shared%20Documents/Kavi,%20Jess,%20Diana%201%20on%201s/ODL%20and%20Park%20Name%20DR%20in%20BCDC/BCDC%20Dataset%20Record%20Creation%20-%20Form%20Responses.docx?d=w71a6db6ab83949178740382e2f4fcc72&csf=1&web=1&e=PMlcKs) with as must info as possible - responsible: @kgorana - deadline: 2024-06-14
  - [x] Inform @JLWade and @meyerdarcie of the fields I don't have an answer to - responsible: @kgorana - deadline: 2024-06-20
  - [x] Find the answer to URL field in the form - responsible: @kgorana - deadline: 2024-06-27
  - [x] Find which a generic contact/s to give in the form - responsible: @meyerdarcie and @JLWade - deadline: 2024-07-02
  - [x] Find the answer to Lifecycle Event field in the form - responsible: @kgorana and @JLWade - deadline: 2024-06-27
- [x] Editor completes it in 'Draft' status - responsible: @JLWade - deadline: 2024-07-02
- [x] Members review it - responsible: @meyerdarcie - deadline: 2024-07-26
- [x] start with ODL checklist now - responsible: @kgorana - deadline: 2024-07-03

## Dependencies
- **Blocked by** response from DataBC answer to the ticket opened for getting answers to a couple questions so that we can submit the record
- **Blocking** #123

### Relevant documentation as reference**
 [Metadata Creation Workflow posted on BCDC website](https://bcgov.github.io/data-publication/pages/images/wf_MetadataCreation.svg)

## Definition of Ready
- [x] Acceptance criteria are included
- [x] Wireframes are included (if applicable)
- [x] Design / Solution is accepted by Product Owner (if applicable)
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

### In progress
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] Work is traceable in GitHub

### PO Review
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

Note: 
- The form needs to be completed, submitted, and approved before being able to publish the record
- Refer to Darcie's note about API prep in the [comment ](https://github.com/bcgov/parks-data-register/issues/507#issuecomment-2206471918)here

**Comment by kgorana** [comment]
Useful for this ticket: https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/311_core_metadata_standard.pdf

**Comment by kgorana** [comment]
moving to blocked until we have all interested parties reviewed the metadata draft record

**Comment by JLWade** [comment]
moving to done

**Comment by LindsayMacfarlane** [comment]
@Dianadec this ticket looks like it should be closed?
