### ISSUE TITLE
Share findings from DUP users' emails to ParkInfo for June 2024

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-data-register#508]
## Description
Use learned UX Research skills to share themes and/or feedback from DUP users' emails sent to ParkInfo in June 2024

## Acceptance Criteria
* A report is shared with the stakeholders on what was found out from the emails
* Be time sensitive
* Only use the skills already learned

## Development Checklist
- [ ] Extracting of dataset
- [ ] Cleaning the data
- [ ] Grouping themes to find labels that can be used (and create columns for each group aka finding metadata)
- [ ] Thematic analysis
- [ ] Interpreting the findings (keeping in mind the research objectives (TBD))
- [ ] Sharing a user research report that summarizes those interpretations

## Definition of Ready
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

### In progress
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
### Code review
  - [ ] Code is peer reviewed and has passed CI/CD tests
### QA
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
### PO Review
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

## Notes
- [Reference Link](https://survicate.com/blog/user-research-analysis/#:~:text=Qualitative%20analysis%20helps%20you%20interpret)
-

**Comment by JLWade** [comment]
moving to blocked until we decide if we want to do this

**Comment by LindsayMacfarlane** [comment]
@Dianadec - another ticket related specifically to Kavi's learnings. Assuming we can close or delete? @JLWade - do you know if there was any initial analysis to support this ticket?

**Comment by LindsayMacfarlane** [comment]
Confirmed with Diana and Jess that this ticket is no longer needed. Closing.
