### ISSUE TITLE
Transfer of data into another format

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-data-register#512]
#### Description:
Help @JLWade with transfer of [Admin Alignment meeting outcomes](https://app.mural.co/t/bcparks2575/m/bcparks2575/1716335523673/7ae0bcd986404dcad1b165a8f54739334ede3d46?sender=ud472c472644927a92faa4344 )from their notes in Miro/Mural to Word doc so that she can use that material to create a document to share out to others. It's helpful to her if this is done before the end of this week.

#### Acceptance Criteria:
- [x] The Word doc has title, purpose, and steps written out in bullet form with numbers to new sections.
- [x] The [Word doc ](https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7BB884AD9F-EFF9-41BC-80A1-99612A4DEB23%7D&file=Admin%20Alignment%20Process%20Summary.docx&action=default&mobileredirect=true)is sent to Jess by 07/11/2024

#### Development Checklist:
- [x] Get access to the workshop board 
- [x] Start transferring the data into a Word doc
- [x] Make edits - deadline: 07/11/2024
- [x] Send the file to Jess

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [x] Acceptance criteria are included
- [x] Wireframes are included (if applicable)
- [x] Design / Solution is accepted by Product Owner (if applicable)
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] Work is traceable in GitHub

- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by kgorana** [comment]
moving to PO review because the initial work asked is completed

**Comment by JLWade** [comment]
thanks for doing this Kavi - moving to done

**Comment by kgorana** [comment]
can I close this ticket?
