### ISSUE TITLE
[M] DR: CSV export of park name register with all fields

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-data-register#516]
#### Description:

We need an export of the park name register with all fields to support getting an open data license. (one-time thing)

#### Acceptance Criteria:
- [x] attach the no sql workbench file to this ticket and provide link to download the workbench file on their machine.
- [ ] include instructions/blog post on how the no sql workbench works

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Refinement notes: @meyerdarcie  to clarify needs with @JLWade

**Comment by cameronpettit** [comment]
Snapshots of the dbs:

[output_audit_table.csv](https://github.com/user-attachments/files/16516194/output_audit_table.csv)
[output_main_table.csv](https://github.com/user-attachments/files/16516193/output_main_table.csv)

**Comment by manuji** [comment]
Tested and verified that the instructions how to install the NoSQL Workbench and the link to the data model has been documented in the GitHub repo. 

Passing this to PO review. 



![Image](https://github.com/user-attachments/assets/0ec09b23-f2c9-4eec-b1b2-9d9d9d85add8)

**Comment by meyerdarcie** [comment]
Moving this to done as ticket is complete - will create new one if there are follow up tasks for open data license.
