### ISSUE TITLE
Share term-end learnings

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-data-register#519]
Share my learnings in the past 1 year with Jess and/or Diana in any format of my choice :)

## AC
- [ ] lessons learned file is completed
- [ ] arranged a meeting with Jess
- [ ] meeting is completed, and file is shared

## Definition of Done
In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] Work is traceable in GitHub

PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
@Dianadec - another Kavi specific ticket. Can we close or delete? Were there any outcomes from this ticket that were shared? 

cc @JLWade

**Comment by LindsayMacfarlane** [comment]
Confirmed with Diana and Jess that this ticket is no longer needed. Closing.
