### ISSUE TITLE
Get familiar with UX Principles

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-data-register#523]
As a part of one of the PDP goals, I want to gain hands-on experience in UX Design and Research. I will do a foundational course to help me get a basic understanding of that realm.

From the Certification course of [Google UX Design](https://www.coursera.org/google-certificates/ux-design-certificate?utm_source=google&utm_medium=institutions&utm_campaign=sou--youtube__med--social__cam--youtube-gwg-certscourse-UX-cert__geo--Global__con--youtube-UX-certs), I have shortlisted the following modules for myself to do:
- [ ] [Intro to UX](https://www.youtube.com/watch?v=2QQQtiFwXjU&list=PLTZYG7bZ1u6oHnGp4Ib3n0y-CmFQdTW6r&index=2)
- [ ] [2 Ways to Share UX Research Insights](https://www.youtube.com/watch?v=reDUTXNV7jU&list=PLTZYG7bZ1u6oHnGp4Ib3n0y-CmFQdTW6r&index=15)

**Comment by LindsayMacfarlane** [comment]
@Dianadec - this ticket appears to be specific to Kavi - assuming we can delete or close? Thoughts?

**Comment by LindsayMacfarlane** [comment]
Confirmed with Diana and Jess that this ticket is no longer needed. Closing.
