### ISSUE TITLE
A&R: Creating a re-usable sub area template

### ISSUE THREAD

**Issue by meredithom** [bcgov/parks-data-register#531]
#### Description:

We've been running into an issue where when new sub areas are to be added they sometimes have fields missing that our db requires. This ticket is to create a template or form that has all required fields for a sub area so it's easy to submit a request for a new one to be added.

#### Acceptance Criteria:
- [ ] template has all required fields as defined by our database 
- [ ]  template can be easily shared 

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- Investigate the use of [CHEFS](https://digital.gov.bc.ca/bcgov-common-components/common-hosted-form-service/)
-

**Comment by Dianadec** [comment]
@davidclaveau is this something you were working on? Meredith mentioned you may have had something setup :)

**Comment by Dianadec** [comment]
@davidclaveau all good!! Thanks for clarifying. I'll mark this ticket as a dupe/closed :)
