### ISSUE TITLE
[L] Address *HIGH RISK* data register security vulnerabilities

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#542]
#### Description:
As a team, we should address security vulnerabilities before they become an issue. There are currently 14 high risk vulnerabilities identified.  https://github.com/bcgov/parks-data-register/security/dependabot

#### Acceptance Criteria:
- [ ] each of the high priority vulnerabilities have been addressed/fixed

#### Development Checklist:

- [x] Determine which vulnerabilities we want to tackled (note: thinking high)
- [x] Come up with approach (i.e., does each vulnerability need a ticket in the backlog?)
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
@LindsayMacfarlane a good one to bring up at next refinement.

**Comment by cameronpettit** [comment]
All of the security vulnerabilities deal with dependencies of dependencies being out of date. This means we cannot directly address the security vulnerabilities, only update our immediate dependencies to their latest versions and hope that they in turn are addressing the security vulnerabilities. Packages have been updated to the latest version as of https://github.com/bcgov/parks-data-register/pull/550 and https://github.com/bcgov/parks-data-register/pull/551.

**Comment by manuji** [comment]
@cameronpettit could you please let me know what sort of testing is best for this ticket? Does the changes impact the project code or is it just github settings only?

**Comment by manuji** [comment]
Thank you @cameronpettit

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Smoke tested the test Data registry and everything looks good. 
* Moving to PO review.

**Comment by LindsayMacfarlane** [comment]
Thank you @cameronpettit for addressing the immediate dependencies. And thank you @manuji for conducting the smoke test. 

Approved. Moving to done.
