### ISSUE TITLE
[L] Create Form Engine that can be reused

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#98]
This ticket is to implement Forms Engine V2 and add it to the modularization package.

There’s 2 factors to this: 

- creating a unified form control engine that dynamically handles the values and functionalities of each field in a form (mostly complete already). The engine should handle various form options:
- disabled/enabled field state
- field validation
- invalid styling
- invalid state information (reasons the field is invalid)
- tooltips

Creating a family of input types that extend the form engine. Some of these common form types could include:

- text (single line)
- text (multiline)
- number
- money
- picklist
- date
- time
- multiselect
- typeahead
- toggle
- radio group
- checkbox group
- wysiwyg

It would be advantageous to make the form engine accept custom input types, validation types,  etc. For example - the datepicker we currently use is already extended from a public package (BsDatePicker). To save us the effort of building our own datepicker (we need to do this anyways), having the engine accept custom inputs is key - otherwise we need to include BsDatePicker as a dependency.

**Acceptance Criteria:**

- Form Engine V2 created
- Core engine built
- Critical input fields are created:
  - text entry (single and multiline)
  - picklist (single and multiselect)
  - typeahead (single and multiselect)
  - Form engine V2 deployed to existing ngds-toolkit
- Examples and documentation are important - this package will be used across multiple projects. Ensure documentation is up to date

**Comment by cameronpettit** [comment]
@JLWade I've finally got something deployable for this. I decided to focus my efforts on making a solid base form engine that can be easily extended into necessary input types - the tradeoff being that I've only made a handful of input types so far. However, I've built the engine in a way that it ties in seamlessly with Angular's default form functionality, meaning if an input type isnt available as part of this engine, you can still custom build your own to work alongside the provided inputs. Currently, the following input types are built:

- text entry (single and multiline)
- picklist (single and multiselect)
- typeahead (single and multiselect)

These should cover all the cases we need for Data Registry from the designs I've seen so far, except for a datepicker (which I foresee taking a while to get right in package format, so maybe we don't need to funnel more time into it yet). 

Tooltips are another feature not yet implemented.

I would like to update the AC for this ticket to remove the inputs & features that haven't yet been made so we can get this moving along (it looks like this was originally made for A&R). We can always come back in the future and make more inputs for the engine as required. What do you think?

In lieu of documentation, a simple showcase app is live at https://digitalspace.github.io/ngds-toolkit/.

**Comment by JLWade** [comment]
Good call @cameronpettit, I have updated the AC to those fields. Let me know if anything else needs to be updated

**Comment by cameronpettit** [comment]
Looks good. I have no PRs to attach this issue to and no real QA requirements. If @manuji wants to peruse the showcase app she is welcome to, but other than that, this issue is completed. @JLWade I will leave moving this to QA/PO Review/Done up to you... not sure how you would like to proceed.

**Comment by JLWade** [comment]
will move to done - testing can happen when we use form engine for Data Rgister
